- server_helpers.R
- ui.R
switched layout to shinydashboard
> Shiny dashboard

- ui.R
- www/custom.css
> header update

- server.R
- server_helpers.R
- ui_tabpanel_benchmark.R
- ui_tabpanel_bmrplots.R
- ui_tabpanel_import.R
- ui_tabpanel_partialdep.R
- ui_tabpanel_predictionplot.R
- ui_tabpanel_summary.R
- ui_tabpanel_task.R
- ui_tabpanel_train_and_predict.R
Still needs to improve, but I guess ok-ish for now
> Nicer dashboardBody

- server.R
- server_helpers.R
- ui.R
I added the possibility to import OpenML datasets within the import tab aswell as within the predict tab.
> closes #3 added possibility to import OpenML Datasets

- server.R
- server_helpers.R
- ui.R
- ui_tabpanel_learners.R
- ui_tabpanel_task.R
- ui_tabpanel_train_and_predict.R
Quite a huge change.
When this is merged we have a new tabPanel for the learner selection.
Here one can select learners and change their param settings.
Also probability estimation is possible for classif tasks.
In the benchmark panel one can then choose between the preselected learners.
This also applies for the train & predict panel.
> New tabPanel for learner selection and construction

- server.R
- ui.R
- ui_tabpanel_benchmark.R
I added shinyjs to simply hide unused arguments (like stratification for regression and iterations for "LOO", "Holdout" and "RepCV")
> closes #7 - moreover adds shinyjs

- server.R
- server_helpers.R
- ui.R
- ui_tabpanel_browse_openml.R
I added a new import tabpanel to browse for OpenML datasets
> added function to browse in OpenML datasets

- server.R
- server_helpers.R
- ui_tabpanel_learners.R
Changes:
* We have input fields and buttons now for setting the hyper parameters
* Changes in the inputs are kept when adding/removing a learner
* changing the predict type is now also kept when learners change
* added support for changing the threshold when predicting probabilities
Open issues:
* Untyped parameters: We need to think about how to deal with this. Currently they are passed down to ````makeLearner()````as characters, so they actually only work when the param value is of type character
> Improve Learner tabPanel

- server_learners.R
tabBox now doesn't rerender anymore every time a param is changed
> mini fix for the learner tabBox

- server_helpers.R
- server_train_and_predict.R
- ui.R
- ui_tabpanel_train_and_predict.R
- www/custom.css
What changed:
* No submenus for train, predict, performance anymore. Divided in a tabBox instead
* Performance measures for probability predictions works now as well
* Predictions can be downloaded as .csv files now
The panel can surely still be improved so I'd leave #27 open for discussion.
> Prettifies train & predict panel and closes #18

- server_benchmark.R
- server_helpers.R
- ui_helpers.R
- ui_tabpanel_task.R
- ui_tabpanel_train_and_predict.R
- www/custom.css
Mainly removing unnecessary boxes and handling missing input values.
@Coorsaa 
Would merging this cause problems on your side? If so this PR can wait a bit.
> Some small UI improvements

- server_data_summary.R
- ui_tabpanel_preprocessing.R
I added a button on top to undo the last data preprocessing step.
> added "undo last change" button to preprocessing

- server_benchmark.R
- server_data_summary.R
- server_helpers.R
- server_import.R
- server_learners.R
- server_task.R
- server_train_and_predict.R
- ui_tabpanel_browse_openml.R
- ui_tabpanel_import.R
- ui_tabpanel_train_and_predict.R
- www/custom.css
This closes #40 and partially fixes #45.
I did not change anything in the visualization panel and also the train, predict panel is not fully done.
But we'll work on both soon so let's leave that for then.
@Coorsaa 
Let's have a look at it tomorrow together and eventually merge then.
> Handle missing reactive objects. Closes #40

- server_data_summary.R
- ui_tabpanel_preprocessing.R
I added a possibility to convert single variables to factors, numerics or integers. Moreover I updated the already existing preproc methods as discussed in #33 .
> closes #44 and #33 convert variable and preproc updates

- ui_tabpanel_browse_openml.R
- ui_tabpanel_import.R
- ui_tabpanel_summary.R
- ui_tabpanel_train_and_predict.R
Merging the last commits vanished all data tables on my machine (OS X, Safari).
Adding back DT:: fixed the problem for me.
@Coorsaa 
Can you check if this is working for you know as well please?
> Fix DataTables

- server_helpers.R
- server_learners.R
* Nicer UI for the Hyperparameters and Predict types
* Allow predict type "se" for regression tasks
* Fix Issues:
- #54 
- #59 (I think. I didn't specifically try fixing this but seemed to have done it by refactoring the code a bit. At least I can't reproduce in this branch. Let me know if it happens for you.)
> Improve learner tab

- server_helpers.R
- server_learners.R
- server_train_and_predict.R
Also input width for thresholds was increased
> Close #59 close #54

- .gitignore
- server.R
* The app stops running in R now automatically when closing the browser window (this is especially handy for non RStudio users (like me :) )
* Added a gitignore file
> 2 small "improvements"

- server_helpers.R
- server_helpers_learners.R
- server_helpers_train_and_predict.R
- server_train_and_predict.R
- server_visualisation.R
- ui_tabpanel_train_and_predict.R
* Some UI improvements for the train and the performance section
* For all tabs in this section the input and exception handling has been improved
> Improvements for the train and predict panel

- server_data_summary.R
- ui_tabpanel_summary.R
Now, one can simply choose the visualised variable by clicking on the summary datatable
> improve data visualisation

- server_helpers_train_and_predict.R
- server_helpers_visualisation.R
- server_visualisation.R
as visualisation option within the train and predict panel
> added variable importance plots

- server_import.R
removed unnecessary code for openml import
> minor cleanup

- server_benchmark.R
- server_helpers.R
- server_train_and_predict.R
- ui.R
- ui_helpers.R
- ui_tabpanel_benchmark.R
Some UI improvements and bug fixes.
New feature:
The different ResampleDesc Types are now fully configureable: E.g: added "split" for Subsample and Holdout and "reps" and "folds" for RepCV
> Closes #69 improves the benchmark panel

- server_benchmark.R
- server_visualisation.R
- ui_tabpanel_benchmark.R
Also the input handling was a bit improved
> Enables measure selection for bmr plots

- server.R
- server_helpers.R
- server_train_and_predict.R
Title says it all.
Most importantly errors of `train()` are now fetched. Shame on us for not doing this earlier 😄
> Better exception and input handling for train/predict

- server.R
- server_data_summary.R
- server_explanations.R
- server_helpers_train_and_predict.R
- server_tuning.R
- server_visualisation.R
- ui.R
- ui_tabpanel_benchmark.R
- ui_tabpanel_import.R
- ui_tabpanel_learners.R
- ui_tabpanel_preprocessing.R
- ui_tabpanel_report.R
- ui_tabpanel_summary.R
- ui_tabpanel_task.R
- ui_tabpanel_train_and_predict.R
- ui_tabpanel_tuning.R
Help texts can now be switched on and of for all parts of the app.
> adding help to the app

- helpers/helpers_general.R
- helpers/helpers_learners.R
- helpers/helpers_train_and_predict.R
- server/learners.R
- server/preprocessing.R
- server/train_and_predict.R
- ui/learners.R
- ui/train_and_predict.R
- www/custom.css
Happy days,
we can train logreg models now 💃 
Also the boxes for the hyperparameters have been restructured so they are smaller, which saves a lot of scrolling.
> nicer learner section. closes #96

- helpers/helpers_general.R
- helpers/helpers_learners.R
- helpers/helpers_train_and_predict.R
- helpers/helpers_tuning.R
- server.R
- server/benchmark.R
- server/learners.R
- server/preprocessing.R
- server/task.R
- server/train_and_predict.R
- server/tuning.R
- ui/benchmark.R
- ui/task.R
Sorry, this PR got a bit diverse:
* Lot's of fixes for the app stability when learner can't be constructed, trained etc.
* Some prettifying of the UI here and there
* Bug fix for tuning: We were calling `tuneParams` with a string, so params of the learner section had no effect
* Task panel got an update: Nicer UI and we also support observation weights now
> stability, ui, bugs, task

- helpers/helpers_general.R
- helpers/helpers_import.R
- server/benchmark.R
- server/import.R
- server/learners.R
- server/preprocessing.R
- server/report.R
- server/summary.R
- server/task.R
- server/train_and_predict.R
- server/tuning.R
- ui/import.R
* Inputs moved to our blue sidebar
* Added checks for data existence in all panels to better inform user
> Small update for the import panel

- server/preprocessing.R
- ui/preprocessing.R
* added download button for processed data
* fixed a bug where the old data frame still showed after importing another dataset
* nicer looking prep preproc_go button
> Small update for preprocessing

- helpers/helpers_train_and_predict.R
- report.Rmd
- server.R
- server/benchmark.R
- server/preprocessing.R
- server/summary.R
- server/train_and_predict.R
- ui.R
- ui/benchmark.R
- ui/preprocessing.R
- ui/summary.R
- ui/train_and_predict.R
Since plotly does not properly work for plotLearnerPrediction we keep (so far) the normal ggplots in the t&p section.
> created plotly plots for summary, feature selection and bmr plots
